### ISSUE TITLE
Prepare for June workshop

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/project_issues#54]
- [x] Figure out goals
    - WL1 feature parity for new site https://github.com/ModellingWebLab/WebLab/issues/68
    - Add minimal required features to demonstrate the Kylie case study (create issues for these in the Epic)
- [x] Invite attendees #55
- [x] Get working WL2 ready to launch
    - [x] Plan who will work on what
    - [x] Create issues and add to epic, assign them to people

What features do we need to have working? We should probably have 'minimal viable' hacky solution that we know we can get ready in time, and 'ideal' scenario with things closer to what they should eventually be.

@MichaelClerx how is the fitting currently being done for the Kylie case study? This will determine the hacky approach!

Ideal scenario:
- Re-work front-end data model per comments in https://github.com/ModellingWebLab/project_issues/wiki/Workshop-notes-2018
    - Include ExperimentalData, FittingSpec and FittingResult
    - Rename Experiment as Prediction
    - Fitting spec can be just pints code
    - Requires at least views to upload data & fitting spec, run fit, view individual fitting results (i.e. parameter distributions) - do we need more here than in Aidan's prototypes?
    - Don't need guided fitting GUI for workshop?
    - Hopefully viewing experimental data and comparing to a prediction can use existing views so will be trivial to add
- Back-end forward simulations using cellmlmanip etc
     - This is probably not achievable in 1 month! So do we need to park activity here and focus on what's needed to run fits first? Does it matter if the forward simulations performed as part of a fit are not the same as those users can run directly?
- Add parameter fitting to back-end web service

Later features out of scope for workshop:
- Running experiments within an isolated environment e.g. Docker
- Improvements to protocol language
- Triple store and metadata searching

**Comment by jonc125** [comment]
@mirams @MichaelClerx - I would welcome your thoughts on what we need to be able to demonstrate on 3rd June!

**Comment by MichaelClerx** [comment]
@mirams in particular we were just discussing what "The Kylie Testcase" is. Just fitting to sine waves? Or methods 1-3 as well? We could quite easily do a method-4-on-lots-of-models, that's on my to-do list anyway

**Comment by mirams** [comment]
I think Method 4 is fine. We've got the various cells' worth of data and various models to try, having that web labbed would be great and show the power of what we are trying to achieve.

[method-4-on-lots-of-models is in the Sanmitra repo - don't do it all again yourself!]

I am a bit worried that there is too much for @michael and your team to do to get there in 6 weeks?!

**Comment by mirams** [comment]
Especially good if we can, for instance, show predictions of the fitted models under other protocols (e.g. IV curve or two).

**Comment by MichaelClerx** [comment]
Combining protocols is an added difficulty :D
But we can probably hack that into the syntax aidan was using

**Comment by MichaelClerx** [comment]
> I am a bit worried that there is too much for @michael and your team to do to get there in 6 weeks?!

We were just discussing this. Some points of interest:

- We don't necessarily need to have the new code generation back end in place for this stuff, although @tamuri and I will keep trying
- Sarah starts today, and will help @jonc125 with the front-end
- We need to be able to show data in the front-end

**Comment by MichaelClerx** [comment]
But we should discuss this further in the meeting tomorrow :-)

**Comment by jonc125** [comment]
Re Gary's comments
1. Being able to have the one (sine wave) fitting spec in the Web Lab, then connect it up to different models and different datasets (independently) and compare the results (in the same way we compare predictions) would certainly make a good demo to aim at!
2. Showing predictions of the fitted models under other protocols might be too much of a stretch for June, as it's another set of logic flows in the front-end.

**Comment by mirams** [comment]
OK! If we follow Kylie method it should be just a single dataset (current trace) per fit, but ideally we can then repeat with different datasets.

**Comment by jonc125** [comment]
Exactly.

**Comment by MichaelClerx** [comment]
All 9 cells for example :-)
