### ISSUE TITLE
Epic 3: Update WebLab deploy to use weblab-fc

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/project_issues#59]
- [ ] Checking simulation results for moderated examples still look the same https://github.com/ModellingWebLab/weblab-fc/issues/24
- [ ] weblab-fc changes to ensure it generates the meta info needed for plotting etc
    - [ ] Converting HDF5 outputs to CSV - capability is there, it just needs to be called. We need to decide whether this is done when running the protocol (so outputs are stored as CSV on disk, not HDF5) or merely when sending the data to the front-end (so the Django code extracts CSV on-the-fly when needed and sends it compressed - better use of disk space but maybe takes longer to display results due to extra processing).
    - [ ] Write metadata CSV files for outputs & plots
        - [ ] First pass can use `get_protocol_interface` to determine units
        - [ ] Second pass should add units info to generated model and pass this through in the environments
    - [ ] Write _plot_data.csv files for each graph
        * Fc-runner now uses the more general plot_data.csv suffix test
        * First column is x, subsequent columns are y data
        * Needs to be written by plotting.py:create_plot
        * Maybe don’t create png when we write this instead? WL doesn’t need the png! That is, creating the png is useful when weblab-fc is being run separately by someone to do a simulation so they have directly visible results. But when run via the WebLab interface the png file is ignored so it's a waste of disk space to create it.
    - [ ] Write 'success' file on completion
- [ ] Change fc-runner to use weblab-fc for simulations
    * We'll still need pycml as long as we use Aidan's fitting implementation, unless that can switch to weblab-fc too?

**Comment by mirams** [comment]
Just added you @kwabenantim and @MichaelClerx to discuss how we get this done, would be nice to have only one bit of code generation software to be maintaining!

**Comment by MichaelClerx** [comment]
I think we basically got https://github.com/ModellingWebLab/project_issues/issues/58 done so this is all about switching over the "deployment" version, which I haven't ever touched
