### ISSUE TITLE
Epic 6: Dataset support

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/project_issues#62]
Continuing the work done in preparation for the workshop

- Main ticket with to-do list: https://github.com/ModellingWebLab/WebLab/issues/131

Further items:
- [ ] Tests for front-end code
- [ ] Comparing datasets to each other
- [ ] Comparison with multiple predictions
- [ ] General infra for entities etc. https://github.com/ModellingWebLab/WebLab/issues/203
- [ ] Annotation --> Part of Epic 7 #63 
- [ ] UI for overview / searching available data https://github.com/ModellingWebLab/WebLab/issues/93
- [ ] Data format https://github.com/ModellingWebLab/WebLab/issues/29

**Comment by MichaelClerx** [comment]
Stretch goal: Work with community https://github.com/ModellingWebLab/project_issues/issues/72
